jump-app-micros:
  enabled: true

# Global variables
global:
  appsDomain: apps.sanlab.sandbox1571.opentlc.com
  # Jump microservices settings
  apps:
    front-javascript:
      build: is
      imagestream: nodejs:latest
      imagestreamNamespace: openshift
      versions:
        - v1
      type: nodejs
      gitRepo: https://github.com/autstudent/jump-app-typescrypt-react.git
    back-golang:
      build: dockerfile
      versions:
        - v1
      gitRepo: https://github.com/acidonper/jump-app-golang.git
      type: golang
    back-python:
      build: is
      imagestream: python:latest
      imagestreamNamespace: openshift
      versions:
        - v1
      gitRepo: https://github.com/acidonper/jump-app-python.git
      type: python
    back-springboot:
      build: is
      imagestream: java:latest
      imagestreamNamespace: openshift
      versions:
        - v1
      gitRepo: https://github.com/acidonper/jump-app-java-springboot.git
      type: java
